version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fraudguard-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=FraudGuard2026_! # Senin şifrenle güncelledik
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  # 2. .NET Web API Servisi
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: fraudguard-backend
    ports:
      - "5217:8080"
    environment:
      # Veritabanı adı FraudGuard ve şifre FraudGuard2026_! olarak güncellendi
      - ConnectionStrings__DefaultConnection=Server=db;Database=FraudGuard;User Id=sa;Password=FraudGuard2026_!;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  # 3. React Frontend Servisi
  frontend:
    build:
      context: ./Client/react-ui
      dockerfile: Dockerfile
    container_name: fraudguard-frontend
    ports:
      - "3000:80" # Konteyner içindeki 80 (Nginx) portunu dışarıya 3000 olarak açıyoruz
    depends_on:
      - backend

volumes:
  mssql-data: # Veritabanının konteyner kapandığında silinmemesi için kalıcı disk alanı
