// <auto-generated>
//     Bu dosya tools/gen_auth_fields.py tarafindan URETILMISTIR.
//     Kaynak: docs/authfinancialapprove.csv
//     ELLE DUZENLEMEYIN - yeniden uretimde degisiklikler kaybolur.
// </auto-generated>
using System;

namespace FraudGuard.Domain.DomainObjects.TransactionProcessing
{
    /// <summary>
    /// AUTHFINANCIALAPPROVE yetkilendirme mesajinin ham alanlari.
    /// <para>
    /// Tum alanlar nullable'dir ve bu kasitlidir: <c>null</c> = alan bu islemde
    /// gonderilmedi, <c>false</c> = gonderildi ve hayir. Fraud degerlendirmesinde
    /// "bilinmiyor" ile "hayir" ayni sey degildir; nullable tipler bu ayrimi
    /// derleme aninda zorunlu kilar (ornegin <c>!input.Auth.PinExist</c> derlenmez,
    /// yazarin <c>input.Auth.PinExist == false</c> demesi gerekir).
    /// </para>
    /// <para>
    /// Kokte karsiligi olan alanlar icin (Amount, Location, RRN, MerchantId, MccKodu)
    /// kural yazarken <b>koku</b> kullanin; buradakiler ham, donusturulmemis degerlerdir.
    /// </para>
    /// </summary>
    public class AuthMessageFields
    {
        /// <summary>Primary Key</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ID (NUMBER(19))</remarks>
        public long? Id { get; set; }

        /// <summary>Modülün karar verdiği kuruma dönülen cevap kodu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RESPONSECODE (VARCHAR2(3))</remarks>
        public string? ResponseCode { get; set; }

        /// <summary>modülün karar verdiği cevap kodu açıklaması</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RESPONSEDESCRIPTION (VARCHAR2(150))</remarks>
        public string? ResponseDescription { get; set; }

        /// <summary>yapılan işlemde alınan hatayı tanımlayan mesaj kodunun detayı. Örnek: CRC00057</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MESSAGECODE (VARCHAR2(10))</remarks>
        public string? MessageCode { get; set; }

        /// <summary>Farklı modül veya CRCMetodlarına yapılan istekler sonrasında alınan hatanın kaynağını belirtir.(CCM,PSP,PSM,VIT vs.)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INNERMESSAGEFROM (NUMBER(2))</remarks>
        public int? InnerMessageFrom { get; set; }

        /// <summary>Farklı modül veya CRCMetodlarına yapılan istekler sonrasında alınan hatayı tanımlayan mesaj kodu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INNERMESSAGECODE (VARCHAR2(10))</remarks>
        public string? InnerMessageCode { get; set; }

        /// <summary>İşlemin yapıldığı kartın CRC_CARD tablosunda bulunan ID'sini belirtir. (Foreign Key)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CARDID (NUMBER(19))</remarks>
        public long? CardId { get; set; }

        /// <summary>Referans numarası, kredi veya banka kartı kullanılarak yapılan işlemler de dahil olmak üzere, herhangi bir finansal işleme atanan benzersiz bir tanımlayıcıdır. Referans numarası, teknolojik olarak oluşturulur ve tek bir işlem için belirlenir</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.REFERENCENUMBER (VARCHAR2(17))</remarks>
        public string? ReferenceNumber { get; set; }

        /// <summary>TRANSACTIONOBJECTID alanı değerli bankacılık işlemleri için üretilen transactionobjectid'nin tutulması için oluşturumuştur. Yapılan işlemlerin APP_JOURNAL tablosuyla ilişkilendirilebilmesi için kullanılmaktadır.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TRANSACTIONOBJECTID (VARCHAR2(32))</remarks>
        public string? TransactionObjectId { get; set; }

        /// <summary>Orijinal işlemin TransactionObjectId'sini tutar.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ORGTRANSACTIONOBJECTID (VARCHAR2(32))</remarks>
        public string? OrgTransactionObjectId { get; set; }

        /// <summary>İşlemin türünü belirten koddur. (SA- Satış, NA- NakitAvans vb.)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TRANSACTIONCODE (VARCHAR2(5))</remarks>
        public string? TransactionCode { get; set; }

        /// <summary>Transaction kodu ile beraber işlemin tipini belirten alt kod alanıdır.(TransactionCode : SA, TransactionSubCode : EC - Satış Ecommerce işlemi vb.)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TRANSACTIONSUBCODE (VARCHAR2(5))</remarks>
        public string? TransactionSubCode { get; set; }

        /// <summary>İşlemin yapıldığı konumun yerel para birim kodunu tutar. (Türkiye için 949 vb.)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.LOCALCURRENCYCODE (VARCHAR2(3))</remarks>
        public string? LocalCurrencyCode { get; set; }

        /// <summary>İşlemin yapıldığı konumun yerel para birimi cinsinden işlem tutarını tutar.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.LOCALAMOUNT (NUMBER(26,2))</remarks>
        public decimal? LocalAmount { get; set; }

        /// <summary>Kart verenin(issuer) işlemi işleyeceği para birimi kodu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.BILLINGCURRENCYCODE (VARCHAR2(3))</remarks>
        public string? BillingCurrencyCode { get; set; }

        /// <summary>Kart verenin(issuer) işlemi işleyeceği para birimi türünden miktar</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.BILLINGAMOUNT (NUMBER(26,2))</remarks>
        public decimal? BillingAmount { get; set; }

        /// <summary>İşlemin müşteriye yansıtıldığı para birimi kodu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.PROVISIONCURRENCYCODE (VARCHAR2(3))</remarks>
        public string? ProvisionCurrencyCode { get; set; }

        /// <summary>İşlemin müşteriye yansıtıldığı para birimi cinsinden miktarı</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.PROVISIONAMOUNT (NUMBER(26,2))</remarks>
        public decimal? ProvisionAmount { get; set; }

        /// <summary>(1:YI, 2:YD)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.PROVISIONCURRENCYTYPE (NUMBER(1))</remarks>
        public int? ProvisionCurrencyType { get; set; }

        /// <summary>Orijinal işlemin local amountu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ORGLOCALAMOUNT (NUMBER(26,2))</remarks>
        public decimal? OrgLocalAmount { get; set; }

        /// <summary>Orijinal işlemin billing amountu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ORGBILLINGAMOUNT (NUMBER(26,2))</remarks>
        public decimal? OrgBillingAmount { get; set; }

        /// <summary>orijinal işlemin provizyon amountu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ORGPROVISIONAMOUNT (NUMBER(26,2))</remarks>
        public decimal? OrgProvisionAmount { get; set; }

        /// <summary>PSP Source Code :</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.SOURCECODE (NUMBER(3))</remarks>
        public int? SourceCode { get; set; }

        /// <summary>gönderen bankanın bkm tarafından verilen benzersiz ID'si.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ACQUIRERID (VARCHAR2(11))</remarks>
        public string? AcquirerId { get; set; }

        /// <summary>ATM = 0, POS = 1 ...</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TERMTYPE (NUMBER(1))</remarks>
        public int? TermType { get; set; }

        /// <summary>İş yeri numarası (MID)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MERCHANTNUMBER (VARCHAR2(15))</remarks>
        public string? MerchantNumber { get; set; }

        /// <summary>041 - Unique acquirer terminal ID</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TERMINALID (VARCHAR2(15))</remarks>
        public string? TerminalId { get; set; }

        /// <summary>- 1-25 Kart Kabul Edenin Adı veya ATM Konumu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.LOCATION (VARCHAR2(40))</remarks>
        public string? Location { get; set; }

        /// <summary>Satıcı kategori kodları (MCC), bir kredi kartı veren kuruluş tarafından müşterilerin belirli bir kart kullanarak yaptıkları alışverişleri kategorize etmek için kullanılan dört haneli sayılardır. Satıcı kategori kodlarının birden fazla anlamı vardır.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MERCHANTCATEGORYCODE (VARCHAR2(4))</remarks>
        public string? MerchantCategoryCode { get; set; }

        /// <summary>İşlemde pin gelip gelmediğini belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.PINEXIST (NUMBER(1))</remarks>
        public bool? PinExist { get; set; }

        /// <summary>İşlemde pin kontrolü yapılıp yapılmaması gerektiği kararını verir</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.REQUIREDCHECKPIN (NUMBER(1))</remarks>
        public bool? RequiredCheckPin { get; set; }

        /// <summary>POINT OF SERVICE ENTRY MODE: POS/ATM üzerinden işlemin nasıl yapıldığını ve POS cihazının Pin giriş kapasitesinin tutulduğu alandır. İşlemin nasıl yapıldığı belirtir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.POSENTRYMODE (VARCHAR2(2))</remarks>
        public string? PosEntryMode { get; set; }

        /// <summary>POS'un şifre giriş yeteneği gönderilmektedir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.PINENTRYMODE (NUMBER(1))</remarks>
        public int? PinEntryMode { get; set; }

        /// <summary>Kart vade dolum tarihi</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CARDEXPIREDATE (VARCHAR2(4))</remarks>
        public string? CardExpireDate { get; set; }

        /// <summary>Card varlık kontrolü yapılıp yapılmayacağını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CARDPRESENT (NUMBER(1))</remarks>
        public bool? CardPresent { get; set; }

        /// <summary>İşlemde CVV2 alanı gelip gelmediğini tutan flag. CVV2(kart güvenlik kodu)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CVV2EXIST (NUMBER(1))</remarks>
        public bool? Cvv2Exist { get; set; }

        /// <summary>İşlemin iptal olup olmadığını belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.REVERSED (NUMBER(1))</remarks>
        public bool? Reversed { get; set; }

        /// <summary>İşlemin iptal işlemi olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.REVERSAL (NUMBER(1))</remarks>
        public bool? Reversal { get; set; }

        /// <summary>işlemin kısmi iptal olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.PARTIAL (NUMBER(1))</remarks>
        public bool? Partial { get; set; }

        /// <summary>İşlemin repeat işlemi olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.REPEAT (NUMBER(1))</remarks>
        public bool? Repeat { get; set; }

        /// <summary>işlemin advice işlemi olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ADVICE (NUMBER(1))</remarks>
        public bool? Advice { get; set; }

        /// <summary>İşlemin EMV işlemi olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.EMVTRANSACTION (NUMBER(1))</remarks>
        public bool? EmvTransaction { get; set; }

        /// <summary>İşlemin temassız işlem olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CONTACTLESS (NUMBER(1))</remarks>
        public bool? Contactless { get; set; }

        /// <summary>İşlemin AccountVerification işlemi olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ACCOUNTVERIFICATION (NUMBER(1))</remarks>
        public bool? AccountVerification { get; set; }

        /// <summary>İşlemin manyetik olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MAGNETICTRANSACTION (NUMBER(1))</remarks>
        public bool? MagneticTransaction { get; set; }

        /// <summary>İşlemin fallback işlemi olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.FALLBACK (NUMBER(1))</remarks>
        public bool? Fallback { get; set; }

        /// <summary>işlemin 3dsecure işlemi olup olmadığını tutan flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.THREEDSECURE (NUMBER(1))</remarks>
        public bool? ThreeDSecure { get; set; }

        /// <summary>İşlemin Recurring işlemi olup olmadığını belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RECURRING (NUMBER(1))</remarks>
        public bool? Recurring { get; set; }

        /// <summary>İşlemin QR işlemi olup olmadığını belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.QRTRANSACTION (NUMBER(1))</remarks>
        public bool? QrTransaction { get; set; }

        /// <summary>işlemin preauthorization işlemi olup olmadığını belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.PREAUTHORIZATION (NUMBER(1))</remarks>
        public bool? PreAuthorization { get; set; }

        /// <summary>işlemin maskeli kart işlemi olup olmadığını belirten flag</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MASKEDCARDTRANSACTION (NUMBER(1))</remarks>
        public bool? MaskedCardTransaction { get; set; }

        /// <summary>İşlemin çapraz işlem olup olmadığını belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CROSSTRANSACTION (NUMBER(1))</remarks>
        public bool? CrossTransaction { get; set; }

        /// <summary>F048 PDS 22</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.SINGLETAPCAPABLE (NUMBER(1))</remarks>
        public bool? SingleTapCapable { get; set; }

        /// <summary>F048 PDS 22</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.SINGLETAPINDICATOR (NUMBER(1))</remarks>
        public bool? SingleTapIndicator { get; set; }

        /// <summary>İşlemin mail order işlemi olup olmadığını belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MAILORDER (NUMBER(1))</remarks>
        public bool? MailOrder { get; set; }

        /// <summary>işlemin e-commerce işlemi olup olmadığını belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ECOMMERCE (NUMBER(1))</remarks>
        public bool? Ecommerce { get; set; }

        /// <summary>işlemde authentication adımının atlanıp atlanmaması gerektiğini belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.SKIPAUTHENTICATION (NUMBER(1))</remarks>
        public bool? SkipAuthentication { get; set; }

        /// <summary>işlemin World işlemi olup olmadığını belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.WORLDTRANSACTION (NUMBER(1))</remarks>
        public bool? WorldTransaction { get; set; }

        /// <summary>İşlemde vade tarihinin gelip gelmediğini belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.EXPIREDATEEXIST (NUMBER(1))</remarks>
        public bool? ExpireDateExist { get; set; }

        /// <summary>İşlemde track2 datasının gelip gelmediğini belirten flag. Kartın manyetik şeridine basılan ve kartın fiziksel kullanımı durumunda provizyon için gerekli olan kart bilgilerini içeren özel bir veri kümesidir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TRACK2EXIST (NUMBER(1))</remarks>
        public bool? Track2Exist { get; set; }

        /// <summary>İşlemde karta issuer script dönülüp dönülmeyeceği bilgisini veren flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ISSUERSCRIPTEXIST (NUMBER(1))</remarks>
        public bool? IssuerScriptExist { get; set; }

        /// <summary>Track2 datasının uzunluk bilgisi</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TRACK2LENGTH (VARCHAR2(2))</remarks>
        public string? Track2Length { get; set; }

        /// <summary>Retrieval Reference Number (RRN) ISO 8583 standardına dayalı olarak bir kart işlemini tanımlayan 12 karakterlik bir kimlik numarasıdır. RRN'nin standart formatı, yetkilendirme tarihini ve saatini içerir, bu da onu bir dereceye kadar benzersiz kılar.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RRN (VARCHAR2(12))</remarks>
        public string? Rrn { get; set; }

        /// <summary>System Trace Audit Number (STAN) kart sahibinin bankası tarafından oluşturulan ve bir işlemi tanımlamak için kullanılabilen bir numaradır. STAN, en çok kart sahibinin bankasında dahili olarak kullanılan bir izleme kimlik numarasıdır. Her zaman altı haneli bir kod olduğundan, kod 999,999'dan sonra sıfırlandığı için gerçekten benzersiz değildir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.STAN (VARCHAR2(6))</remarks>
        public string? Stan { get; set; }

        /// <summary>Otorizasyon kodu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.AUTHCODE (VARCHAR2(6))</remarks>
        public string? AuthCode { get; set; }

        /// <summary>Kalan limit miktarı</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.AVAILABLELIMIT (NUMBER(26,2))</remarks>
        public decimal? AvailableLimit { get; set; }

        /// <summary>Online = 1, Offline = 2, Advice = 3</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MSGSTATE (NUMBER(2))</remarks>
        public int? MsgState { get; set; }

        /// <summary>BKM : F061- SF11</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.POSTERMINPUTCAPABILITY (NUMBER(1))</remarks>
        public int? PosTermInputCapability { get; set; }

        /// <summary>Yurt içi edinilmiş satın alma işlemleri için BKM Unique Merchant Id</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.BKMUNIQUEMERCHANTID (VARCHAR2(8))</remarks>
        public string? BkmUniqueMerchantId { get; set; }

        /// <summary>CCM modülü tarafından analiz edilerek modüle dönülen offline pin doğrulama sonucu :</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TRANSACTIONPINSTATUS (NUMBER(1))</remarks>
        public int? TransactionPinStatus { get; set; }

        /// <summary>3D Secure doğrulama datasının gelip gelmediğini belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CAVVAVAILABLE (NUMBER(1))</remarks>
        public bool? CavvAvailable { get; set; }

        /// <summary>3D Secure doğrulama sonucu. BKM MANUEL Table 8 (CAVV Result Codes).</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CAVVRESULTCODE (VARCHAR2(1))</remarks>
        public string? CavvResultCode { get; set; }

        /// <summary>Nothing = '0',</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.THREEDSECURETYPE (VARCHAR2(1))</remarks>
        public string? ThreeDSecureType { get; set; }

        /// <summary>Visa = 'V', MasterCard = 'M', Discover = 'D', BKMExpress = 'B', GO = 'G', NotExists = 'N'</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CAVVDATATYPE (VARCHAR2(1))</remarks>
        public string? CavvDataType { get; set; }

        /// <summary>İşlem Taksit sayısı</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INSTALLMENTCOUNT (NUMBER(2))</remarks>
        public int? InstallmentCount { get; set; }

        /// <summary>İşlemin taksitli olup olmadığını belirtir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INSTALLMENTFLAG (NUMBER(1))</remarks>
        public bool? InstallmentFlag { get; set; }

        /// <summary>İşlem faiz oranı</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INTERESTRATE (NUMBER(15,7))</remarks>
        public decimal? InterestRate { get; set; }

        /// <summary>İşlem ücreti</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.FEEAMOUNT (NUMBER(26,2))</remarks>
        public decimal? FeeAmount { get; set; }

        /// <summary>MasterCard ile ilgili bir iade talebini orijinal talebiyle eşleştirmek için kullanılan eşleşme anahtarı genellikle Referans Numarası veya İşlem Kimliği olarak adlandırılır. Bu anahtar, iadenin doğru bir şekilde orijinal satın alma veya işlemle ilişkilendirilmesini sağlar.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.BNETSETTLEMENTDATE (VARCHAR2(6))</remarks>
        public string? BnetSettlementDate { get; set; }

        /// <summary>işlemin fatura ödeme işlemi olup olmadığını belirten flagdir</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INVOICEPAYMENT (NUMBER(1))</remarks>
        public bool? InvoicePayment { get; set; }

        /// <summary>İşlemin mobilden gelip gelmediğini belirten flag</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MOBILETRANSACTION (NUMBER(1))</remarks>
        public bool? MobileTransaction { get; set; }

        /// <summary>PDS 26 - Cüzdan platformu kullanılarak gönderilen işlemleri tanımlayacak alt alanı içerir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.WALLETPROGRAMDATA (VARCHAR2(3))</remarks>
        public string? WalletProgramData { get; set; }

        /// <summary>BKM MANUEL PDS42 ilk 2 hanesi. Security Level Indicator</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MOBILEECITYPE (VARCHAR2(2))</remarks>
        public string? MobileEciType { get; set; }

        /// <summary>BKM MANUEL PDS 32 - Mastercard veya BKM tarafından mobil cihaza atanan Merchant ID</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MOBILEASSIGNEDID (VARCHAR2(6))</remarks>
        public string? MobileAssignedId { get; set; }

        /// <summary>PDS 23 - Form Factor Indicator</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.DEVICETYPE (VARCHAR2(2))</remarks>
        public string? DeviceType { get; set; }

        /// <summary>BKM MANUEL Table 15 (POS Data) - n1, position 10</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CARDHOLDERACTIVATEDTERMLEVEL (NUMBER(1))</remarks>
        public bool? CardHolderActivatedTermLevel { get; set; }

        /// <summary>Gecikmiş otorizasyon olduğunu belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.DEFERREDAUTH (NUMBER(1))</remarks>
        public bool? DeferredAuth { get; set; }

        /// <summary>Table 27 -- Merchant Initiated Result Code</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MITINDICATOR (VARCHAR2(1))</remarks>
        public string? MitIndicator { get; set; }

        /// <summary>PDS 87 ? Card Validation Code Result</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CVCRESULTCODE (VARCHAR2(1))</remarks>
        public string? CvcResultCode { get; set; }

        /// <summary>CCM doğrulama işleminin sonucu.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CRYPTOGRAMVERIFICATIONRESULT (NUMBER(1))</remarks>
        public int? CryptogramVerificationResult { get; set; }

        /// <summary>BKM MANUEL F048 PDS 22</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.SINGLETAPPINREQUEST (NUMBER(1))</remarks>
        public bool? SingleTapPinRequest { get; set; }

        /// <summary>(0:finansal tablo ilişkisi olmayan 1:provision, 2:payment, 3:clearingonline)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TRANSACTIONDESTINATIONTYPE (NUMBER(1))</remarks>
        public int? TransactionDestinationType { get; set; }

        /// <summary>TransactionDestinationId</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TRANSACTIONDESTINATIONID (NUMBER(19))</remarks>
        public long? TransactionDestinationId { get; set; }

        /// <summary>İşlemin money send işlemi olup olmadığını gönsteren flag</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MONEYSEND (NUMBER(1))</remarks>
        public bool? MoneySend { get; set; }

        /// <summary>Taksitli işlemlerde alınan faiz miktarını tutar.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INTERESTAMOUNT (NUMBER(26,2))</remarks>
        public decimal? InterestAmount { get; set; }

        /// <summary>İşlemi veritabanına ekleyen kullanıcının sicilini içerir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INSERTUSERCODE (VARCHAR2(10))</remarks>
        public string? InsertUserCode { get; set; }

        /// <summary>Kaydın en son güncellenme tarihini tutar.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RECORDDATE (DATE)</remarks>
        public DateTime? RecordDate { get; set; }

        /// <summary>Kaydı güncelleyen son kişinin sicilini tutar.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RECORDUSERCODE (VARCHAR2(10))</remarks>
        public string? RecordUserCode { get; set; }

        /// <summary>En son güncellemenin yapıldığı branchi belirtir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RECORDBRANCHCODE (VARCHAR2(6))</remarks>
        public string? RecordBranchCode { get; set; }

        /// <summary>Kayıt üzerinde yapılan son güncellemenin yapıldığı ekranı belirtir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RECORDSCREENCODE (VARCHAR2(10))</remarks>
        public string? RecordScreenCode { get; set; }

        /// <summary>Request'e ait obeject Id</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RECORDREQUESTOBJECTID (VARCHAR2(36))</remarks>
        public string? RecordRequestObjectId { get; set; }

        /// <summary>Kayıt üzerinde yapılan son güncellemenin yapıldığı kanalı belirtir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RECORDCHANNELCODE (NUMBER(2))</remarks>
        public int? RecordChannelCode { get; set; }

        /// <summary>Kayıt yaratılma tarihi</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.RECORDCREATEDATE (DATE)</remarks>
        public DateTime? RecordCreateDate { get; set; }

        /// <summary>Online işlemin şifresinin geçerli olup olmadığını belirten flag.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ONLINEPINVALID (NUMBER(1))</remarks>
        public bool? OnlinePinValid { get; set; }

        /// <summary>Taksitli işlemlerde Taksit tablosu ile kurulan foreign key bağlantısıdır.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INSTALLMENTHEADERID (NUMBER(19))</remarks>
        public long? InstallmentHeaderId { get; set; }

        /// <summary>Ücretli işlemlerde İşlem Ücret tablosu ile kurulan foreign key bağlantısıdır.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.TRANSACTIONFEEID (NUMBER(19))</remarks>
        public long? TransactionFeeId { get; set; }

        /// <summary>İşlemin yapıldığı konumdaki tarih</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.LOCALDATE (DATE)</remarks>
        public DateTime? LocalDate { get; set; }

        /// <summary>yapılan işlemin Yurt içi tutar karşılığı</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.DOMESTICAMOUNT (NUMBER(26,2))</remarks>
        public decimal? DomesticAmount { get; set; }

        /// <summary>Ön provizyonun ne kadar aktif kalacağı gün sayısı F61-12 ve 13.hanelerde gönderilir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.PREAUTHVALIDDAYCOUNT (NUMBER(2))</remarks>
        public int? PreAuthValidDayCount { get; set; }

        /// <summary>İşlemin HCE işlem tipini belirten enum değeridir. İşlem HCE işlemi değil ise None olarak işaretlenir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.HCETRANSACTIONTYPE (NUMBER(1))</remarks>
        public int? HceTransactionType { get; set; }

        /// <summary>İşlem HCE kart işlemi ise kullanılan token pana(sanal kart numarası) ait HCECARD id'si tutulur.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.HCECARDID (NUMBER(19))</remarks>
        public long? HceCardId { get; set; }

        /// <summary>işlemin takas eşleşme tamamlanma son tarihi</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.COMPLETIONEXPIREDATE (DATE)</remarks>
        public DateTime? CompletionExpireDate { get; set; }

        /// <summary>İşlemin orjinal kaydının takas eşleşme tamamlanma son tarihi(gelen ilk tarih)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ORIGINALCOMPLETIONEXPIREDATE (DATE)</remarks>
        public DateTime? OriginalCompletionExpireDate { get; set; }

        /// <summary>İşlemin Incremental bir işlem mi olduğunu belirtir. Incremental Transaction, kredi kartı işlemlerinde, bir ödemenin ilk işlem tutarına ek olarak sonradan yapılan küçük artışları ifade eder.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INCREMENTAL (NUMBER(1))</remarks>
        public bool? Incremental { get; set; }

        /// <summary>işlemin afd olduğunu belirten flagdir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.AFDTRANSACTION (NUMBER(1))</remarks>
        public bool? AfdTransaction { get; set; }

        /// <summary>orjinal domestic amountu tutan alan.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ORIGINALDOMESTICAMOUNT (NUMBER(26,2))</remarks>
        public decimal? OriginalDomesticAmount { get; set; }

        /// <summary>Issuer yerine verilen otorizasyon işlemlerine Stand-In(Yerine) Otorizasyon denir. Bazı yerlerde STIP olarak da geçmektedir. (Stand In Provision)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.STANDIN (NUMBER(1))</remarks>
        public bool? Standin { get; set; }

        /// <summary>Kurum Kodu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INSTITUTIONCODE (VARCHAR2(10))</remarks>
        public string? InstitutionCode { get; set; }

        /// <summary>İşleme ait Pan Sequence Number, Kartın basım sırasını belirtir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.PSN (NUMBER(2))</remarks>
        public int? Psn { get; set; }

        /// <summary>İşlemin eşleniksiz iade olarak gelip gelmediğini belirtir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.UNMATCHEDREFUND (NUMBER(1))</remarks>
        public bool? UnmatchedRefund { get; set; }

        /// <summary>İade işlemlerinde orjinal işlemin provizyon kodu</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ORGSALETRANAUTHCODE (VARCHAR2(6))</remarks>
        public string? OrgSaleTranAuthCode { get; set; }

        /// <summary>İade işlemlerinde orjinal işlem tutarı</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ORGSALETRANAMOUNT (NUMBER(26,2))</remarks>
        public decimal? OrgSaleTranAmount { get; set; }

        /// <summary>İade işlemlerinde orjinal işlemin RRN değeri</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.ORGSALETRANRRN (VARCHAR2(12))</remarks>
        public string? OrgSaleTranRrn { get; set; }

        /// <summary>Üye işyeri bulunduğu şehir.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MERCHANTCITY (VARCHAR2(13))</remarks>
        public string? MerchantCity { get; set; }

        /// <summary>Üye işyeri adı.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MERCHANTNAME (VARCHAR2(25))</remarks>
        public string? MerchantName { get; set; }

        /// <summary>Kartın Kimlik Numarası</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.CARDIDENTITYID (NUMBER(19))</remarks>
        public long? CardIdentityId { get; set; }

        /// <summary>İşlemin iade işlemi olduğunu belirten alandır.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.REFUND (NUMBER(1))</remarks>
        public bool? Refund { get; set; }

        /// <summary>İşlemin surcharge amount taşıdığını belirten alandır.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.SURCHARGE (NUMBER(1))</remarks>
        public bool? Surcharge { get; set; }

        /// <summary>Mobile ECI Indicator (genişletildi: 1 -&gt; 2 karakter)</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.MOBILEECIINDIC (VARCHAR2(2))</remarks>
        public string? MobileEciIndic { get; set; }

        /// <summary>Incremental işlemlerin orjinal işlem ile eşleştirilebilmesi için kullanılan unique ID değeridir.(9 karakter Banknet Reference Number + 4 karakter Settlement date) Visa 16 karakter 62.2</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.INCREMENTALTRACEID (VARCHAR2(16))</remarks>
        public string? IncrementalTraceId { get; set; }

        /// <summary>MasterCard veya Visa ile ilgili bir iade talebini orijinal talebiyle eşleştirmek için kullanılan eşleşme anahtarı genellikle Referans Numarası veya İşlem Kimliği olarak adlandırılır. Bu anahtar, iadenin doğru bir şekilde orijinal satın alma veya işlemle ilişkilendirilmesini sağlar.</summary>
        /// <remarks>AUTHFINANCIALAPPROVE.BNETTRACEID (VARCHAR2(16))</remarks>
        public string? BnetTraceId { get; set; }
    }
}
